# Generated by Django 5.1.7 on 2025-03-30 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
