# Generated by Django 5.1.7 on 2025-03-12 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='codigo_validacao',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('certificado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='certificados.certificado')),
            ],
        ),
    ]
