# Generated by Django 5.1.7 on 2025-03-30 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_alter_certificado_data_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='media_curricular',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
