# Generated by Django 5.1.7 on 2025-03-12 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_remove_certificado_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='codigo_validacao',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
