# Generated by Django 5.1.7 on 2025-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_alter_certificado_classificacao_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='identificador_matricula',
            field=models.CharField(default=1, help_text='Identificador único para geração do número de matrícula (ex: I para Informática, M para Mecânica)', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matricula',
            name='nivel_classe',
            field=models.CharField(default='13', max_length=20),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='numero_matricula',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='turno',
            field=models.CharField(choices=[('MANHA', 'Manha'), ('TARDE', 'Tarde'), ('NOTURNO', 'Noturno')], max_length=10),
        ),
    ]
