# Generated by Django 5.1.7 on 2025-04-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_curso_identificador_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='cargo_diretor',
            field=models.CharField(default='Directora do Instituto Politécnico Industrial do Calumbo', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='numero_processo',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='nome_instituicao',
            field=models.CharField(default='Instituto Politecnico Industrial do Icolo e Bengo', max_length=200),
        ),
    ]
