# Generated by Django 5.1.7 on 2025-03-30 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_alter_certificado_media_curricular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='classificacao_final',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='prova_aptidao_profissional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
