# Generated by Django 5.1.7 on 2025-04-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_alter_certificado_cargo_diretor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='conta_habilitada',
            field=models.BooleanField(default=False, help_text='Se a conta está habilitada para fazer login'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='ultimo_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
