# Generated by Django 5.1.7 on 2025-04-09 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0005_aluno_conta_habilitada_aluno_email_aluno_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='provincia',
            field=models.CharField(choices=[('BENGO', 'Bengo'), ('BENGUELA', 'Benguela'), ('BIE', 'Bié'), ('CABINDA', 'Cabinda'), ('CUANDO_CUBANGO', 'Cuando Cubango'), ('CUANDO', 'Cuando'), ('CUANZA_NORTE', 'Cuanza Norte'), ('CUANZA_SUL', 'Cuanza Sul'), ('CUNENE', 'Cunene'), ('HUAMBO', 'Huambo'), ('HUILA', 'Huíla'), ('LUANDA', 'Luanda'), ('ICOLO E BENGO', 'Icolo e Bengo'), ('LUNDA_NORTE', 'Lunda Norte'), ('LUNDA_SUL', 'Lunda Sul'), ('MALANJE', 'Malanje'), ('MOXICO', 'Moxico'), ('CASSAI ZAMBEZE', 'Cassai Zambeze'), ('NAMIBE', 'Namibe'), ('UIGE', 'Uíge'), ('ZAIRE', 'Zaire'), ('OUTRO', 'Outro (Estrangeiro)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='certificados.matricula', unique=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='numero_processo',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
