# Generated by Django 5.1.7 on 2025-04-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0006_alter_aluno_provincia_alter_certificado_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='tipo_identificacao',
            field=models.CharField(choices=[('BI', 'Bilhete de Identidade'), ('PASSAPORTE', 'Passaporte')], default='BI', max_length=50),
        ),
    ]
