# Generated by Django 5.1.7 on 2025-04-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0007_alter_aluno_tipo_identificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='carga_horaria',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao_anos',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
