# Generated by Django 5.1.7 on 2025-04-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0008_remove_disciplina_carga_horaria_alter_aluno_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='password',
            new_name='senha',
        ),
    ]
