# Generated by Django 5.1.7 on 2025-04-13 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0009_rename_password_aluno_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='ano_letivo',
            field=models.CharField(default='2024-2025', max_length=9),
        ),
        migrations.AlterField(
            model_name='pedidocorrecao',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.aluno'),
        ),
    ]
