# Generated by Django 5.1.7 on 2025-04-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0010_alter_matricula_ano_letivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='categoria',
            field=models.CharField(choices=[('COMPONENTE SOCIO-CULTURAL', 'Componente Socio-cultural'), ('COMPONENTE CIENTIFICA', 'Componente Cientifica'), ('COMPONENTE TECNOLOGICA E PRATICA', 'Componente Tecnologica e Pratica')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('MEDIO', 'Curso Médio'), ('BASICO', 'Curso Básico')], default='Curso Médio', max_length=10),
        ),
    ]
