# Generated by Django 5.1.7 on 2025-04-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0012_alter_certificado_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='emissor_identificacao',
            field=models.CharField(default='Direção Nacional de Identificação', max_length=100),
        ),
    ]
