# Generated by Django 5.1.7 on 2025-05-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0013_alter_aluno_emissor_identificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='cargo_diretor',
            new_name='cargo_de_direção',
        ),
    ]
