# Generated by Django 5.1.7 on 2025-06-03 14:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0014_rename_cargo_diretor_certificado_cargo_de_direção'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracaoNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=20)),
                ('ano_letivo', models.CharField(default='2024/2025', max_length=9)),
                ('turma', models.CharField(default='TI12AD', max_length=20)),
                ('codigo_verificacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes_declaracoes/')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now)),
                ('carimbo_oleo', models.BooleanField(default=True, help_text='Indica se a declaração foi autenticada com carimbo à óleo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('emitido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declaracoes', to='certificados.matricula')),
            ],
            options={
                'verbose_name': 'Declaração de Notas',
                'verbose_name_plural': 'Declarações de Notas',
                'ordering': ['-data_emissao'],
            },
        ),
    ]
