# Generated by Django 5.1.7 on 2025-06-03 14:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0015_declaracaonotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoDeclaracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_numerica', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('declaracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='certificados.declaracaonotas')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificados.disciplina')),
            ],
            options={
                'verbose_name': 'Resultado na Declaração',
                'verbose_name_plural': 'Resultados na Declaração',
                'ordering': ['disciplina__nome'],
                'unique_together': {('declaracao', 'disciplina')},
            },
        ),
    ]
