# Generated by Django 5.1.7 on 2025-06-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0016_resultadodeclaracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracaonotas',
            name='ano_letivo',
            field=models.CharField(default='2024-2025', max_length=9),
        ),
        migrations.AlterField(
            model_name='declaracaonotas',
            name='turma',
            field=models.CharField(default='TI12AD', max_length=20, unique=True),
        ),
    ]
