# Generated by Django 5.1.7 on 2025-06-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0017_alter_declaracaonotas_ano_letivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaracaonotas',
            name='carimbo_oleo',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='cargo_de_direção',
            field=models.CharField(default='Directora do Instituto Politécnico Industrial do Zango', max_length=100),
        ),
        migrations.AlterField(
            model_name='declaracaonotas',
            name='ano_letivo',
            field=models.CharField(max_length=9),
        ),
    ]
