# Generated by Django 5.1.7 on 2025-06-06 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0018_remove_declaracaonotas_carimbo_oleo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocorrecao',
            name='declaracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_correcao', to='certificados.declaracaonotas'),
        ),
        migrations.AddField(
            model_name='pedidocorrecao',
            name='tipo_documento',
            field=models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('DECLARACAO', 'Declaração de Notas')], default='CERTIFICADO', max_length=12),
        ),
        migrations.AlterField(
            model_name='declaracaonotas',
            name='turma',
            field=models.CharField(default='TI12AD', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidocorrecao',
            name='certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_correcao', to='certificados.certificado'),
        ),
    ]
